// This file is auto-generated by @hey-api/openapi-ts

export const $PatientDTO = {
  type: "object",
  properties: {
    uuid: {
      type: "string",
      format: "uuid",
    },
    fullName: {
      type: "string",
    },
    age: {
      type: "integer",
      format: "int32",
    },
    gender: {
      type: "string",
    },
    phoneNumber: {
      type: "string",
    },
    email: {
      type: "string",
    },
  },
} as const;

export const $AdminProfileUpdateRequestDTO = {
  type: "object",
  properties: {
    fullName: {
      type: "string",
    },
    email: {
      type: "string",
    },
  },
  required: ["email", "fullName"],
} as const;

export const $Response = {
  type: "object",
  properties: {
    code: {
      type: "string",
      enum: [
        "INTERNAL_ERROR",
        "ACCESS_DENIED",
        "USER_NOT_FOUND",
        "USER_ALREADY_EXIST",
        "BAD_REQUEST",
        "NOT_FOUND",
        "CREATED",
        "SERVICE_UNAVAILABLE",
        "UNAUTHORIZED",
        "INVALID_INPUT",
        "INVALID_RESPONSE",
        "LOGOUT_RESPONSE",
        "DB_ERROR",
        "IAM_ERROR",
        "AWS_ERROR",
        "ENTITY",
        "OK",
        "UPDATED",
        "UNSUPPORTED_MEDIA_TYPE",
        "CHECK_CONSULT_TIME",
        "INVALID_TIME_DURATION",
        "PAST_START_TIME",
        "SLOT_ALREADY_BOOKED",
        "SLOT_NOT_FOUND",
        "NO_NOTIFICATIONS",
        "NOTIFICATION_MARKED_AS_SEEN",
        "AWS_EVENT_BRIDGE_SCHEDULER_CONFLICT",
        "TOO_MANY_REQUESTS",
        "CONFLICT",
      ],
    },
    data: {
      type: "object",
    },
    message: {
      type: "string",
    },
  },
} as const;

export const $PrescriptionRequestDTO = {
  type: "object",
  properties: {
    medicineName: {
      type: "string",
    },
    dosage: {
      type: "string",
    },
    frequency: {
      type: "string",
    },
    duration: {
      type: "integer",
      format: "int32",
    },
    instructions: {
      type: "string",
    },
    appointmentUuid: {
      type: "string",
      format: "uuid",
    },
  },
  required: [
    "appointmentUuid",
    "dosage",
    "duration",
    "frequency",
    "medicineName",
  ],
} as const;

export const $RegisterPatient = {
  type: "object",
  properties: {
    username: {
      type: "string",
    },
    password: {
      type: "string",
    },
    firstName: {
      type: "string",
    },
    lastName: {
      type: "string",
    },
    age: {
      type: "integer",
      format: "int32",
    },
    gender: {
      type: "string",
    },
    phoneNumber: {
      type: "string",
    },
    email: {
      type: "string",
    },
  },
  required: [
    "age",
    "email",
    "firstName",
    "gender",
    "lastName",
    "password",
    "phoneNumber",
    "username",
  ],
} as const;

export const $SetPasswordDTO = {
  type: "object",
  properties: {
    newPassword: {
      type: "string",
    },
  },
  required: ["newPassword"],
} as const;

export const $ResetPasswordRequest = {
  type: "object",
  properties: {
    token: {
      type: "string",
    },
    newPassword: {
      type: "string",
      maxLength: 128,
      minLength: 8,
    },
  },
  required: ["newPassword", "token"],
} as const;

export const $ResetPasswordResponse = {
  type: "object",
  properties: {
    success: {
      type: "boolean",
    },
    message: {
      type: "string",
    },
  },
} as const;

export const $RefreshTokenRequestDTO = {
  type: "object",
  properties: {
    refreshToken: {
      type: "string",
    },
  },
  required: ["refreshToken"],
} as const;

export const $RefreshTokenResponseDTO = {
  type: "object",
  properties: {
    success: {
      type: "boolean",
    },
    access_token: {
      type: "string",
    },
    refresh_token: {
      type: "string",
    },
    expires_in: {
      type: "integer",
      format: "int64",
    },
    token_type: {
      type: "string",
    },
  },
} as const;

export const $LogoutRequest = {
  type: "object",
  properties: {
    refreshToken: {
      type: "string",
    },
  },
  required: ["refreshToken"],
} as const;

export const $LogoutResponse = {
  type: "object",
  properties: {
    success: {
      type: "boolean",
    },
    message: {
      type: "string",
    },
  },
} as const;

export const $LoginDTO = {
  type: "object",
  properties: {
    username: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
  required: ["password", "username"],
} as const;

export const $LoginResponseDTO = {
  type: "object",
  properties: {
    access_token: {
      type: "string",
    },
    refresh_token: {
      type: "string",
    },
    expires_in: {
      type: "integer",
      format: "int64",
    },
  },
} as const;

export const $ForgotPasswordRequest = {
  type: "object",
  properties: {
    username: {
      type: "string",
    },
  },
  required: ["username"],
} as const;

export const $ForgotPasswordResponse = {
  type: "object",
  properties: {
    success: {
      type: "boolean",
    },
    message: {
      type: "string",
    },
  },
} as const;

export const $AppointmentRequestDTO = {
  type: "object",
  properties: {
    appointmentDate: {
      type: "string",
      format: "date-time",
    },
    reasonForVisit: {
      type: "string",
    },
    status: {
      type: "string",
      enum: [
        "SCHEDULED",
        "COMPLETED",
        "PENDING",
        "CHECK_IN",
        "CANCELLED",
        "NO_SHOW",
        "RESCHEDULED",
        "CLOSED",
      ],
    },
    patientUuid: {
      type: "string",
      format: "uuid",
    },
    doctorUuid: {
      type: "string",
      format: "uuid",
    },
  },
  required: [
    "appointmentDate",
    "doctorUuid",
    "patientUuid",
    "reasonForVisit",
    "status",
  ],
} as const;

export const $DoctorProfileUpdateRequestDTO = {
  type: "object",
  properties: {
    fullName: {
      type: "string",
    },
    specialization: {
      type: "string",
    },
    phoneNumber: {
      type: "string",
      pattern: "^[0-9]{10}$",
    },
    email: {
      type: "string",
    },
    consultationFee: {
      type: "number",
      minimum: 0,
    },
  },
  required: ["email", "fullName", "phoneNumber", "specialization"],
} as const;

export const $ChangePasswordRequest = {
  type: "object",
  properties: {
    currentPassword: {
      type: "string",
    },
    newPassword: {
      type: "string",
      maxLength: 2147483647,
      minLength: 8,
    },
  },
  required: ["currentPassword", "newPassword"],
} as const;

export const $ChangePasswordResponseDTO = {
  type: "object",
  properties: {
    success: {
      type: "boolean",
    },
    message: {
      type: "string",
    },
  },
} as const;

export const $AppointmentSummary = {
  type: "object",
  properties: {
    upcoming: {
      type: "integer",
      format: "int64",
    },
    completed: {
      type: "integer",
      format: "int64",
    },
  },
} as const;

export const $LabReportSummary = {
  type: "object",
  properties: {
    available: {
      type: "integer",
      format: "int64",
    },
  },
} as const;

export const $MedicalRecordSummary = {
  type: "object",
  properties: {
    total: {
      type: "integer",
      format: "int64",
    },
  },
} as const;

export const $NextAppointment = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    time: {
      type: "string",
    },
    doctorName: {
      type: "string",
    },
    specialization: {
      type: "string",
    },
  },
} as const;

export const $PatientDashboardDTO = {
  type: "object",
  properties: {
    patient: {
      $ref: "#/components/schemas/PatientSummary",
    },
    appointments: {
      $ref: "#/components/schemas/AppointmentSummary",
    },
    prescriptions: {
      $ref: "#/components/schemas/PrescriptionSummary",
    },
    medicalRecords: {
      $ref: "#/components/schemas/MedicalRecordSummary",
    },
    labReports: {
      $ref: "#/components/schemas/LabReportSummary",
    },
    nextAppointment: {
      $ref: "#/components/schemas/NextAppointment",
    },
  },
} as const;

export const $PatientSummary = {
  type: "object",
  properties: {
    fullName: {
      type: "string",
    },
  },
} as const;

export const $PrescriptionSummary = {
  type: "object",
  properties: {
    active: {
      type: "integer",
      format: "int64",
    },
  },
} as const;
