// This file is auto-generated by @hey-api/openapi-ts

export type PatientDTO = {
  uuid?: string;
  fullName?: string;
  age?: number;
  gender?: string;
  phoneNumber?: string;
  email?: string;
};

export type AdminProfileUpdateRequestDTO = {
  fullName: string;
  email: string;
};

export type Response = {
  code?:
    | "INTERNAL_ERROR"
    | "ACCESS_DENIED"
    | "USER_NOT_FOUND"
    | "USER_ALREADY_EXIST"
    | "BAD_REQUEST"
    | "NOT_FOUND"
    | "CREATED"
    | "SERVICE_UNAVAILABLE"
    | "UNAUTHORIZED"
    | "INVALID_INPUT"
    | "INVALID_RESPONSE"
    | "LOGOUT_RESPONSE"
    | "DB_ERROR"
    | "IAM_ERROR"
    | "AWS_ERROR"
    | "ENTITY"
    | "OK"
    | "UPDATED"
    | "UNSUPPORTED_MEDIA_TYPE"
    | "CHECK_CONSULT_TIME"
    | "INVALID_TIME_DURATION"
    | "PAST_START_TIME"
    | "SLOT_ALREADY_BOOKED"
    | "SLOT_NOT_FOUND"
    | "NO_NOTIFICATIONS"
    | "NOTIFICATION_MARKED_AS_SEEN"
    | "AWS_EVENT_BRIDGE_SCHEDULER_CONFLICT"
    | "TOO_MANY_REQUESTS"
    | "CONFLICT";
  data?: {
    [key: string]: unknown;
  };
  message?: string;
};

export type code =
  | "INTERNAL_ERROR"
  | "ACCESS_DENIED"
  | "USER_NOT_FOUND"
  | "USER_ALREADY_EXIST"
  | "BAD_REQUEST"
  | "NOT_FOUND"
  | "CREATED"
  | "SERVICE_UNAVAILABLE"
  | "UNAUTHORIZED"
  | "INVALID_INPUT"
  | "INVALID_RESPONSE"
  | "LOGOUT_RESPONSE"
  | "DB_ERROR"
  | "IAM_ERROR"
  | "AWS_ERROR"
  | "ENTITY"
  | "OK"
  | "UPDATED"
  | "UNSUPPORTED_MEDIA_TYPE"
  | "CHECK_CONSULT_TIME"
  | "INVALID_TIME_DURATION"
  | "PAST_START_TIME"
  | "SLOT_ALREADY_BOOKED"
  | "SLOT_NOT_FOUND"
  | "NO_NOTIFICATIONS"
  | "NOTIFICATION_MARKED_AS_SEEN"
  | "AWS_EVENT_BRIDGE_SCHEDULER_CONFLICT"
  | "TOO_MANY_REQUESTS"
  | "CONFLICT";

export type PrescriptionRequestDTO = {
  medicineName: string;
  dosage: string;
  frequency: string;
  duration: number;
  instructions?: string;
  appointmentUuid: string;
};

export type RegisterPatient = {
  username: string;
  password: string;
  firstName: string;
  lastName: string;
  age: number;
  gender: string;
  phoneNumber: string;
  email: string;
};

export type SetPasswordDTO = {
  newPassword: string;
};

export type ResetPasswordRequest = {
  token: string;
  newPassword: string;
};

export type ResetPasswordResponse = {
  success?: boolean;
  message?: string;
};

export type RefreshTokenRequestDTO = {
  refreshToken: string;
};

export type RefreshTokenResponseDTO = {
  success?: boolean;
  access_token?: string;
  refresh_token?: string;
  expires_in?: number;
  token_type?: string;
};

export type LogoutRequest = {
  refreshToken: string;
};

export type LogoutResponse = {
  success?: boolean;
  message?: string;
};

export type LoginDTO = {
  username: string;
  password: string;
};

export type LoginResponseDTO = {
  access_token?: string;
  refresh_token?: string;
  expires_in?: number;
};

export type ForgotPasswordRequest = {
  username: string;
};

export type ForgotPasswordResponse = {
  success?: boolean;
  message?: string;
};

export type AppointmentRequestDTO = {
  appointmentDate: string;
  reasonForVisit: string;
  status:
    | "SCHEDULED"
    | "COMPLETED"
    | "PENDING"
    | "CHECK_IN"
    | "CANCELLED"
    | "NO_SHOW"
    | "RESCHEDULED"
    | "CLOSED";
  patientUuid: string;
  doctorUuid: string;
};

export type status =
  | "SCHEDULED"
  | "COMPLETED"
  | "PENDING"
  | "CHECK_IN"
  | "CANCELLED"
  | "NO_SHOW"
  | "RESCHEDULED"
  | "CLOSED";

export type DoctorProfileUpdateRequestDTO = {
  fullName: string;
  specialization: string;
  phoneNumber: string;
  email: string;
  consultationFee?: number;
};

export type ChangePasswordRequest = {
  currentPassword: string;
  newPassword: string;
};

export type ChangePasswordResponseDTO = {
  success?: boolean;
  message?: string;
};

export type AppointmentSummary = {
  upcoming?: number;
  completed?: number;
};

export type LabReportSummary = {
  available?: number;
};

export type MedicalRecordSummary = {
  total?: number;
};

export type NextAppointment = {
  date?: string;
  time?: string;
  doctorName?: string;
  specialization?: string;
};

export type PatientDashboardDTO = {
  patient?: PatientSummary;
  appointments?: AppointmentSummary;
  prescriptions?: PrescriptionSummary;
  medicalRecords?: MedicalRecordSummary;
  labReports?: LabReportSummary;
  nextAppointment?: NextAppointment;
};

export type PatientSummary = {
  fullName?: string;
};

export type PrescriptionSummary = {
  active?: number;
};

export type GetPatientByIdData = {
  id: number;
};

export type GetPatientByIdResponse = PatientDTO;

export type ChangePatientData = {
  id: number;
  requestBody: PatientDTO;
};

export type ChangePatientResponse = string;

export type DeletePatientData = {
  id: number;
};

export type DeletePatientResponse = unknown;

export type RegisterNewPatientData = {
  requestBody: RegisterPatient;
};

export type RegisterNewPatientResponse = PatientDTO;

export type GetMyProfileResponse = PatientDTO;

export type UpdatePatientData = {
  requestBody: PatientDTO;
};

export type UpdatePatientResponse = PatientDTO;

export type GetResponse = Response;

export type GetDashboardResponse = PatientDashboardDTO;

export type GetAdminProfileResponse = Response;

export type UpdateAdminProfileData = {
  requestBody: AdminProfileUpdateRequestDTO;
};

export type UpdateAdminProfileResponse = Response;

export type TestEmailData = {
  email: string;
};

export type TestEmailResponse = string;

export type CreatePrescriptionData = {
  requestBody: PrescriptionRequestDTO;
};

export type CreatePrescriptionResponse = Response;

export type GetPrescriptionByUuidData = {
  uuid: string;
};

export type GetPrescriptionByUuidResponse = Response;

export type GetPrescriptionByAppointmentUuidData = {
  appointmentUuid: string;
};

export type GetPrescriptionByAppointmentUuidResponse = Response;

export type SetPasswordData = {
  patientId: number;
  requestBody: SetPasswordDTO;
};

export type SetPasswordResponse = unknown;

export type ResetPasswordData = {
  requestBody: ResetPasswordRequest;
};

export type ResetPasswordResponse2 = ResetPasswordResponse;

export type RefreshData = {
  requestBody: RefreshTokenRequestDTO;
};

export type RefreshResponse = RefreshTokenResponseDTO;

export type LogoutData = {
  requestBody: LogoutRequest;
};

export type LogoutResponse2 = LogoutResponse;

export type LoginData = {
  requestBody: LoginDTO;
};

export type LoginResponse = LoginResponseDTO;

export type ForgotPasswordData = {
  requestBody: ForgotPasswordRequest;
};

export type ForgotPasswordResponse2 = ForgotPasswordResponse;

export type ChangePasswordData = {
  requestBody: ChangePasswordRequest;
};

export type ChangePasswordResponse = ChangePasswordResponseDTO;

export type CreateNewAppointmentData = {
  requestBody: AppointmentRequestDTO;
};

export type CreateNewAppointmentResponse = Response;

export type GetPatientAppointmentsData = {
  /**
   * Zero-based page index (0..N)
   */
  page?: number;
  /**
   * The size of the page to be returned
   */
  size?: number;
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: Array<string>;
};

export type GetPatientAppointmentsResponse = Response;

export type GetDoctorAppointmentsData = {
  /**
   * Zero-based page index (0..N)
   */
  page?: number;
  /**
   * The size of the page to be returned
   */
  size?: number;
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: Array<string>;
};

export type GetDoctorAppointmentsResponse = Response;

export type GetAllAppointmentsData = {
  /**
   * Zero-based page index (0..N)
   */
  page?: number;
  /**
   * The size of the page to be returned
   */
  size?: number;
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: Array<string>;
};

export type GetAllAppointmentsResponse = Response;

export type GetDoctorProfileResponse = Response;

export type UpdateDoctorProfileData = {
  requestBody: DoctorProfileUpdateRequestDTO;
};

export type UpdateDoctorProfileResponse = Response;

export type GetAllDoctorsResponse = Response;

export type GetDoctorDashboardResponse = Response;

export type $OpenApiTs = {
  "/api/v1/patient/{id}": {
    get: {
      req: GetPatientByIdData;
      res: {
        /**
         * OK
         */
        200: PatientDTO;
      };
    };
    put: {
      req: ChangePatientData;
      res: {
        /**
         * OK
         */
        200: string;
      };
    };
    delete: {
      req: DeletePatientData;
      res: {
        /**
         * OK
         */
        200: unknown;
      };
    };
  };
  "/api/v1/patient/register": {
    post: {
      req: RegisterNewPatientData;
      res: {
        /**
         * OK
         */
        200: PatientDTO;
      };
    };
  };
  "/api/v1/patient/me": {
    get: {
      res: {
        /**
         * OK
         */
        200: PatientDTO;
      };
    };
    patch: {
      req: UpdatePatientData;
      res: {
        /**
         * OK
         */
        200: PatientDTO;
      };
    };
  };
  "/api/v1/patient/patients": {
    get: {
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/patient/dashboard": {
    get: {
      res: {
        /**
         * OK
         */
        200: PatientDashboardDTO;
      };
    };
  };
  "/api/v1/admin/profile": {
    get: {
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
    put: {
      req: UpdateAdminProfileData;
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/test/email": {
    post: {
      req: TestEmailData;
      res: {
        /**
         * OK
         */
        200: string;
      };
    };
  };
  "/api/v1/prescription": {
    post: {
      req: CreatePrescriptionData;
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/prescription/{uuid}": {
    get: {
      req: GetPrescriptionByUuidData;
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/prescription/appointment/{appointmentUuid}": {
    get: {
      req: GetPrescriptionByAppointmentUuidData;
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/auth/set-password/{patientId}": {
    post: {
      req: SetPasswordData;
      res: {
        /**
         * OK
         */
        200: unknown;
      };
    };
  };
  "/api/v1/auth/reset-password": {
    post: {
      req: ResetPasswordData;
      res: {
        /**
         * OK
         */
        200: ResetPasswordResponse;
      };
    };
  };
  "/api/v1/auth/refresh": {
    post: {
      req: RefreshData;
      res: {
        /**
         * OK
         */
        200: RefreshTokenResponseDTO;
      };
    };
  };
  "/api/v1/auth/logout": {
    post: {
      req: LogoutData;
      res: {
        /**
         * OK
         */
        200: LogoutResponse;
      };
    };
  };
  "/api/v1/auth/login": {
    post: {
      req: LoginData;
      res: {
        /**
         * OK
         */
        200: LoginResponseDTO;
      };
    };
  };
  "/api/v1/auth/forgot-password": {
    post: {
      req: ForgotPasswordData;
      res: {
        /**
         * OK
         */
        200: ForgotPasswordResponse;
      };
    };
  };
  "/api/v1/auth/change-password": {
    patch: {
      req: ChangePasswordData;
      res: {
        /**
         * OK
         */
        200: ChangePasswordResponseDTO;
      };
    };
  };
  "/api/v1/appointment": {
    post: {
      req: CreateNewAppointmentData;
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/appointment/patient": {
    get: {
      req: GetPatientAppointmentsData;
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/appointment/doctor": {
    get: {
      req: GetDoctorAppointmentsData;
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/appointment/admin": {
    get: {
      req: GetAllAppointmentsData;
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/doctor/profile": {
    get: {
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
    patch: {
      req: UpdateDoctorProfileData;
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/doctor": {
    get: {
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
  "/api/v1/doctor/dashboard": {
    get: {
      res: {
        /**
         * OK
         */
        200: Response;
      };
    };
  };
};
